### ISSUE TITLE
Whitespace removed around standalone macro with attribute

### ISSUE THREAD

**Issue by klanchman** [swiftlang/swift-format#689]
When a using standalone macro with an attribute on it, swift-format wants to remove whitespace around the macro.

The following example assumes the default swift-format configuration. Tested on 509.0.0 and `main`.

**Input:**

```swift
@available(iOS 17.0, *)
#Preview("Name") {
  EmptyView()
}
```

**Expected output:** same as input

**Actual output:**

```
Test.swift:1:24: warning: [RemoveLine] remove line break
Test.swift:2:17: warning: [Spacing] remove 1 space
```

```swift
@available(iOS 17.0, *)#Preview("Name"){
  EmptyView()
}
```

**Comment by MarceNN** [comment]
Hi, I have the same problem with XCode 15.1, any solution for this?

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://126948308

**Comment by MarceNN** [comment]
Hi, I couldn't find that issue on apple's tracker.  https://openradar.appspot.com/search?query=126948308
Do you have the link?

**Comment by ahoppen** [comment]
The issue has just been synced to Apple’s issue tracker, which isn’t public. Having it represented in there simplifies planning within Apple. We will post any relevant updates to the GitHub issue as well.
