### ISSUE TITLE
Missing option to allow trailing whitespaces on blank lines

### ISSUE THREAD

**Issue by Frizlab** [swiftlang/swift-format#718]
My goal is to allow this formatting style (screenshot from Xcode settings), which I always use.
<img width="359" alt="Screenshot 2024-04-16 at 22 46 22" src="https://github.com/apple/swift-format/assets/523041/60b586a7-2445-4f3f-a410-3288235f8d61">

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://126948372

**Comment by Frizlab** [comment]
Can we get a status on this issue? Is it planned to be implemented? Would you accept a PR if I implemented it?

**Comment by ahoppen** [comment]
There is no update on this issue at the moment. PRs are always welcome.

**Comment by bnbarham** [comment]
I believe this is actually a dupe of https://github.com/swiftlang/swift-format/issues/801 which has https://github.com/swiftlang/swift-format/pull/804 up

**Comment by Frizlab** [comment]
Respectfully, #801 is a dupe of this. But I’m happy to see other people caring about this!

**Comment by bnbarham** [comment]
> Respectfully, https://github.com/swiftlang/swift-format/issues/801 is a dupe of this

Ah true, I missed that this was an older issue :) I just knew 801 from the PR.

**Comment by Frizlab** [comment]
Implemented in #804. Thanks! ☺️
