### ISSUE TITLE
Don't trim whitespace-only lines

### ISSUE THREAD

**Issue by ValentinWalter** [swiftlang/swift-format#801]
The only thing holding me back from adopting swift-format is the inability to allow trailing whitespace in whitespace-only lines. This is my favorite Xcode feature!

<img width="365" alt="image" src="https://github.com/user-attachments/assets/166b6fb9-96fd-4564-8677-716082cb9201">

Can we change PrettyPrinter to keep the surrounding context's indentation for empty lines, or would that be a breaking change? Can we add something that's based on a configuration to PrettyPrinter? I would love to get the ball rolling if someone can point me to the right place to implement this.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://135215957

**Comment by bnbarham** [comment]
> This is my favorite Xcode feature!

Out of interest, what's your use case for keeping whitespace on blank lines only?

**Comment by ValentinWalter** [comment]
> Out of interest, what's your use case for keeping whitespace on blank lines only?

I love being able to arrow down/up or click on empty lines that are already correctly indented. Makes the editing experience feel more "solid" if that makes sense.

**Comment by allevato** [comment]
My personal feeling on this is that editors that want to provide that functionality should provide a "virtual cursor" where the user can navigate to a location outside the document's horizontal bounds, but only if they start typing there does it insert the spaces. (Naturally, that's out of scope for *this* project.)

Always inserting spaces to fill up otherwise blank lines just feels wasteful.

**Comment by TTOzzi** [comment]
> Always inserting spaces to fill up otherwise blank lines just feels wasteful.

I completely agree with this opinion. 
However, in Xcode, if we turn off the `Including whitespace-only lines` option and perform automatic indentation (`Command + I`), it still inserts spaces according to the indent level even on empty lines. 

In my opinion, if we would like the formatting to behave exactly like Xcode, it might be better to also insert spaces on empty lines according to the indent level. But if the intention is to reduce unnecessary actions, it may be more appropriate to only adjust lines that have incorrect amounts of whitespace to match the indent level. 🤔

**Comment by bnbarham** [comment]
IMO matching Xcode is a non-goal here. If there's general interest, we should definitely consider adding it. The next question there is whether we need both options ("remove trailing whitespace" and "indent blank lines"), or whether just the latter is enough. My preference would be just the latter.

> My personal feeling on this is that editors that want to provide that functionality should provide a "virtual cursor"

I feel somewhat similar, though it's entirely possible that someone could be using very lightweight editors without this sort of feature. It would also mean that the editor has to understand how to indent (though maybe that's as simple as "match previous line").
