### ISSUE TITLE
Xcode feature request: Format File with 'swift-format' on save

### ISSUE THREAD

**Issue by mesqueeb** [swiftlang/swift-format#808]
Xcode 16 has the new `Format File with 'swift-format'` option. I used a 3rd party app to trigger that on file save (⌘S). I think this should be a simple checkbox in the Xcode settings. 🙏🏻

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://136327495

**Comment by ahoppen** [comment]
This would be a request to Xcode, not the `swift-format` open source project. Could you file a feedback for this at http://feedbackassistant.apple.com?

**Comment by jacobsvante** [comment]
@mesqueeb Did you hear anything from Apple about this?
