### ISSUE TITLE
readme: Clarify where to place configuration file so Xcode automatically uses that config

### ISSUE THREAD

**Issue by mesqueeb** [swiftlang/swift-format#809]
Executing `swift format dump-configuration` on macOS 15 shows the default Swift format rules.

I'd like to save this JSON somewhere in my project, so that Xcode automatically uses those rules when tapping `Format File with 'swift-format'` in Xcode 16.

Committing the rules config json to the project, would make the entire team use the same rules as well.

Can we add a section on the README that explains this? I believe any project that has more than 1 person working on it needs this. :tada:

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://136327486

**Comment by mesqueeb** [comment]
as per these docs: https://github.com/swiftlang/swift-format/blob/main/Documentation/Configuration.md#example
I have added a `.swift-format` file with the following contents to my Xcode workspace root:
```json
{
  "version": 1,
  "lineLength": 120,
  "indentation": {
    "spaces": 2
  },
  "maximumBlankLines": 1
}
```
but executing `Format File with 'swift-format'` will not use this configuration. 🤔

**Comment by ahoppen** [comment]
I just tried this and Xcode did pick up the `.swift-format` file in my project’s root. I think a `.swift-format` file should be picked up as long as it is in a parent directory of your source file.

In either case, Xcode not picking up `.swift-format` would be an Xcode issue not an issue with the `swift-format` open source project, so if you’re still seeing this, could you file an issue to Xcode at http://feedbackassistant.apple.com?

**Comment by mesqueeb** [comment]
I'm glad to say that it does work!

Whoever is looking here, be sure to enabled the `"respectsExistingLineBreaks": true` in the config, otherwise swift-format doesn't really format much at all.

Currently I'm using this to try and replicate prettier as much as possible:
```
{
  "version": 1,
  "lineLength": 80,
  "indentation": {
    "spaces": 2
  },
  "maximumBlankLines": 1,
  "respectsExistingLineBreaks": false,
  "lineBreakBeforeControlFlowKeywords": false,
  "lineBreakBeforeEachArgument": true,
  "lineBreakBeforeEachGenericRequirement": true,
  "lineBreakBetweenDeclarationAttributes": false,
  "prioritizeKeepingFunctionOutputTogether": true,
  "indentConditionalCompilationBlocks": true,
  "lineBreakAroundMultilineExpressionChainComponents": true,
  "spacesAroundRangeFormationOperators": true,
  "multiElementCollectionTrailingCommas": true
}
```
`.swift-format` at root of Xcode workspace
