### ISSUE TITLE
The option `--follow-symlinks` can't follow relative symlinks

### ISSUE THREAD

**Issue by kkebo** [swiftlang/swift-format#836]
## Description

The subcommands `lint` and `format` have the option `--follow-symlinks`. However, although it can follow absolute symlinks, it can't follow relative symlinks.

## Steps to reproduce

```console
$ mkdir symlink-test
$ cd symlink-test/
$ echo 'let foo:Int=0' > .foo.swift
$ ln -s .foo.swift bar.swift
$ swift format dump-configuration > .swift-format
$ cd ..
$ swift format lint -rs --follow-symlinks symlink-test/
<unknown>: error: Unable to open .foo.swift: file is not readable or does not exist
```

If the current working directory is the symlink's directory, it works.

```console
$ cd symlink-test
$ swift format lint -rs --follow-symlinks .
.foo.swift:1:9: warning: [Spacing] add 1 space
.foo.swift:1:12: warning: [Spacing] add 1 space
.foo.swift:1:13: warning: [Spacing] add 1 space
```

It's because the following line is using `relativeTo: workingDirectory`.

https://github.com/swiftlang/swift-format/blob/8068ff75e23084bfdc0706a70fa1bc926c9ca71e/Sources/SwiftFormat/Utilities/FileIterator.swift#L152

## Environment

- swift-format (bundled in Swift 6.0.1 toolchain)
- Debian 12 (aarch64)

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://137341926

**Comment by kkebo** [comment]
It seemed that `testFollowSymlinks` failed in macOS. I'll investigate it.

https://ci.swift.org/job/swift-syntax-PR-macOS/4601/console

```
Test Case '-[SwiftFormatTests.FileIteratorTests testFollowSymlinks]' started.
/Users/ec2-user/jenkins/workspace/swift-syntax-PR-macOS/branch-main/swift-format/Tests/SwiftFormatTests/Utilities/FileIteratorTests.swift:37: error: -[SwiftFormatTests.FileIteratorTests testFollowSymlinks] : XCTAssertEqual failed: ("4") is not equal to ("3")
Test Case '-[SwiftFormatTests.FileIteratorTests testFollowSymlinks]' failed (0.699 seconds).
```
