### ISSUE TITLE
swift-format causes a infinite loop on Linux if `.swift-format` is missing

### ISSUE THREAD

**Issue by kkebo** [swiftlang/swift-format#847]
## Description

On Linux, when all ancestor directories do not have `.swift-format`, swift-format causes a infinite loop. `swift-format lint` and `swift-format format` do not work.

## Steps to reproduce

Please make sure that `/`, `/home`, and `/home/<user name>` do not contain `.swift-format`.

```console
$ cd
$ echo 'let foo:Int=0' > test.swift
$ swift format lint test.swift
```

## Expected behavior

```
test.swift:1:9: warning: [Spacing] add 1 space
test.swift:1:12: warning: [Spacing] add 1 space
test.swift:1:13: warning: [Spacing] add 1 space
```

## Actual behavior

swift-format never finishes because of a infinite loop.

## Environment

I use swift-format bundled in the Swift 6.0.1 toolchain.

```console
$ uname -a
Linux Raspberry-beetle 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt2 (2024-10-01) aarch64 GNU/Linux
$ swift --version
Swift version 6.0.1 (swift-6.0.1-RELEASE)
Target: aarch64-unknown-linux-gnu
$ swift format --version
main
$ which swift-format
/home/kebo/.local/bin/swift-format
$ swiftly list
Installed release toolchains
----------------------------
Swift 6.0.1 (in use)

Installed snapshot toolchains
-----------------------------
6.0-snapshot-2024-09-17
```

## Supplement

I think that the root cause is a combination of swift-foundation's `URL` and swift-format's [this line](https://github.com/swiftlang/swift-format/blob/7ee11c7ff95bab851d0ddc1d0071794d9de3065c/Sources/SwiftFormat/API/Configuration.swift#L483).

swift-foundation's `URL` is different from macOS's `URL`.

- On Linux (Swift 6.0.1)
  - `URL(filePath: "/foo", directoryHint: .notDirectory).deletingLastPathComponent().path()`
    - returns `"/"`
  - `URL(filePath: "/foo", directoryHint: .isDirectory).deletingLastPathComponent().path()`
    - returns `""` (empty string)
- On macOS 15.0.1 (Xcode 16.0)
  - Both return `"/"`

On Linux, when I added `print(self.path)` to [the line](https://github.com/swiftlang/swift-format/blob/7ee11c7ff95bab851d0ddc1d0071794d9de3065c/Sources/SwiftFormat/API/Configuration.swift#L483), `self.path` changed as follows.

- `"/foo/bar/baz"`
- `"/foo/bar"`
- `"/foo"`
- `""` (empty string)
- `""` (empty string)
- `""` (empty string)
- ... (infinite loop)

So `self.path == "/"` couldn't return `true` forever.

**Comment by kkebo** [comment]
https://github.com/swiftlang/swift-foundation/pull/969 may fix this issue.

**Comment by kkebo** [comment]
#802 fixed this problem once, but it happened again with #845.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://137738047

**Comment by ahoppen** [comment]
Neither https://github.com/swiftlang/swift-format/pull/802 nor https://github.com/swiftlang/swift-format/pull/845 apply if you’re using swift-format from a Swift 6.0 toolchain because those PRs only got merged into `main`, not into `release/6.0`.

I’m cherry-picking the fixes to 6.0 in https://github.com/swiftlang/swift-format/pull/849

**Comment by kkebo** [comment]
@ahoppen

My comment below is the result of building and testing from source code of the `main` branch with a Swift 6.0 toolchain.

> #802 fixed this problem once, but it happened again with #845.

**Comment by ahoppen** [comment]
Oh, I see. I wasn’t sure if you built from source. Thanks for your detailed analysis.
