### ISSUE TITLE
Hangs indefinitely on Linux

### ISSUE THREAD

**Issue by Cyberbeni** [swiftlang/swift-format#861]
I have tried:
- `swift:6.0.1` docker and run `swift format ./test.swift`
- Inside `ubuntu-latest` GitHub workflow: checkout 600.0.0, `swift build --configuration release --disable-sandbox` and run `./.build/release/swift-format ./test.swift` or `./.build/release/swift-format lint ./test.swift`

Both of these just result in no output and keep running indefinitely.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://138397913

**Comment by ahoppen** [comment]
Sounds like this is https://github.com/swiftlang/swift-format/issues/847.
