### ISSUE TITLE
Don't insert unnecessary (double) space for // inline comments

### ISSUE THREAD

**Issue by ktoso** [swiftlang/swift-format#868]
Swift-format has this really weird behavior of adding an "extra" space for inline comments:

![Screenshot 2024-10-30 at 19 07 50](https://github.com/user-attachments/assets/741d1ba0-b1c4-4274-8199-f5f4ffbbe54b)

from:
```
hello() // says hello
```

to

```
hello()  // says hello
```

This is pretty weird and should not be happening.

**Comment by allevato** [comment]
FWIW, offsetting EOL comments by 2 spaces is just a typographic/style choice that isn't any weirder than the others 🙂 

As of https://github.com/swiftlang/swift-format/pull/776, it can be controlled by the `spacesBeforeEndOfLineComments` configuration setting. I believe it's only available in the 601.0.0 prereleases, though.

**Comment by ktoso** [comment]
Across a bunch languages I worked with this is the first time seeing this so it’s at least uncommon in that sense. 

Good to hear it’s configurable now but pretty the downside nowadays being that the releases are tied to swift hm… 

we can probably consider this solved by that configuration option though.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://138912225

**Comment by ktoso** [comment]
Heh, with further reading I found this is specifically the Google-way https://google.github.io/swift/

I'd be iffy about imposing that specific rule... but since it's configurable I guess we can leave it at that.

**Comment by allevato** [comment]
If we can get the entire community to agree on any set of rules, I'm happy to change them 😅
